---
- hosts: webserver
  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      become: true
      apt:
        name: docker-compose
        state: present

    - name: Create project directory
      file:
        path: "{{ ansible_env.HOME }}/ansible-docker-compose-project"
        state: directory

    - name: Copy application files
      copy:
        src: ../app
        dest: "{{ ansible_env.HOME }}/ansible-docker-compose-project/app"

    - name: Copy Docker Compose file
      copy:
        src: ../docker-compose.yml
        dest: "{{ ansible_env.HOME }}/ansible-docker-compose-project/docker-compose.yml"

    - name: Start application with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: "{{ ansible_env.HOME }}/ansible-docker-compose-project"


